services:
  node:
    build:
      context: .
      dockerfile: .docker/node/Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_GRAPHQL_URL=http://localhost:8000/graphql

networks:
  pos-puc-mvp-02-network:
    driver: bridge
